### ISSUE TITLE
error

### ISSUE THREAD

**Issue by alexzalazar** [Meliodas-rai/Bot#6]
hola meliodas, al querer iniciar el bot (git pull, npm start)  me salta un error:
![Screenshot_20210603-201018](https://user-images.githubusercontent.com/78123735/120740657-ff8f8b00-c4c9-11eb-91a6-68aed6529fd2.png)

**Comment by Meliodas-rai** [comment]
escribe esto

cd Bot

git pull

npm start

Em sex, 4 de jun de 2021 12:16 AM, alexzalazar ***@***.***>
escreveu:

**Comment by alexzalazar** [comment]
xd Eu não entendi é que um amigo me mostrou seu bot e me deu as etapas para baixá-lo. Você poderia explicar em etapas como resolver o erro?

**Comment by Meliodas-rai** [comment]
Jaja eu resolvo ele quando chegar às 1 horas da tarde você de estes
comandos um por um no termux

cd Bot

git pull

npm start

Em sex, 4 de jun de 2021 9:24 AM, alexzalazar ***@***.***>
escreveu:

**Comment by alexzalazar** [comment]
ok te espero xd

**Comment by alexzalazar** [comment]
![Screenshot_20210604-224952](https://user-images.githubusercontent.com/78123735/120876525-8c4c4e80-c587-11eb-969f-57fb3245b0c7.png)
Me desculpe, eu perdi um erro novamente

**Comment by Meliodas-rai** [comment]
Esse erro e aqui, o Pc está desligado então outra hora eu arrumo esse erro
aí

Em sex, 4 de jun de 2021 10:52 PM, alexzalazar ***@***.***>
escreveu:
